### PR TITLE
#158487978 Add User Profile Page

### PR DESCRIPTION
**Pull request by iverenshaguy**
What does this PR do?
This pull request adds the user profile to the app

Description of Task to be completed?

- add user profile API endpoint
- implement user donation addition per donation button click
- add leaderboard API endpoint
- integrate user profile with front endpoint

How should this be manually tested?
N/A

Any background context you want to provide?
N/A

What are the relevant pivotal tracker stories?
#158487978

screen shot 2018-07-06 at 7 42 53 pm

### CODE REVIEW

**Review by otseobande — APPROVED** [review]
- I like the way you paid attention to details and corrected the typo in the user model test. This is nice and you should keep it up.

- You took great initiative implementing the donation service feature along side the profile page design. This is nice and has eased the workload on the next person implementing something donation related. You should keep doing this as it reflects that you care about the product.

- You disabled eslint on some lines where I feel we could refactor and make the codebase look cleaner. In future, I feel you can go ahead and refactor those lines.

**Comment by nouwatinjacob** [comment]
I really commend the effort you put into completing this task. Also, you implemented some other features that are associated with this your task. 
This shows how committed and effective you are in the team. Nice work!
Keep it up

**Review by nouwatinjacob — COMMENTED** [review]
N/A

**Review by nouwatinjacob — APPROVED** [review]
I really commend the effort you put into completing this task. Also, you implemented some other features that are associated with this your task.
This shows how committed and effective you are in the team. Nice work!
Keep it up

**Pull request merged**
