### PR TITLE
#158487965 Users should be able to create/start a new game

### PR DESCRIPTION
**Pull request by nouwatinjacob**
#### What does this PR do?
- This Pull Request save details of a game
#### Description of Task to be completed?
- save the details of a game when a winner emerges
- update game's won if the winner is the authenticated user
#### How should this be manually tested?
- run npm test
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#158487965
#### Screenshots (if appropriate)
N/A
#### Questions:

### CODE REVIEW

**Review by iverenshaguy — COMMENTED** [review]
N/A

**Review by Stylll — COMMENTED** [review]
You have done a great job. However, there is no screenshot of the feature in your PR. You should endeavor to make a PR with a screenshot of the final product so reviewers can have a visual representation of what the feature is about.

**Review by ozimos — COMMENTED** [review]
Good job.
Your PR looks clean and all tests are passing. Keep it up

**Comment by andela-moe** [comment]
Conflicts on your PR. Please do well to resolve and also ensure that you address certain of the issues flagged by HoundCI. Most of them can be resolved. The tool exist to help your codebase attain a good level of quality. Disregarding the issues flagged gives no value to the tool.

**Pull request closed without merging**
